tasks:
  build:
    runner: razorci/php:7.4
    steps:
    - checkout
    - run: echo Build Stage
 # test:
 #   steps:
 #   - run: echo Test Stage
 # deploy:
 #   steps:
 #   - run: echo Deploy Stage
