tasks:
  unit-test:
    runner: razorci/php:7.4
    steps:
    - checkout
    - commands:
      - phpbrew switch 7.2.23
      - composer -V
    steps:
    - cache/pull: composer-cache-{{ checksum "composer.lock" }}
    - run: composer install -n --prefer-dist
    - commands:
      - composer install -n --prefer-dist
